version: '1.0'

services:
  postgres:
    container_name: threads
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=threads
      - POSTGRES_PASSWORD=strongpassword

volumes:
  postgres-data:
